---
# Copyright 2026 Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: import playbook 50-bamboo-verify.yml
  import_playbook: 50-bamboo-verify.yml

- name: import playbook 50-bitbucket-verify.yml
  import_playbook: 50-bitbucket-verify.yml

- name: import playbook 50-confluence-verify.yml
  import_playbook: 50-confluence-verify.yml

- name: import playbook 50-crowd-verify.yml
  import_playbook: 50-crowd-verify.yml

- name: import playbook 50-fisheye-verify.yml
  import_playbook: 50-fisheye-verify.yml

- name: import playbook 50-jira-verify.yml
  import_playbook: 50-jira-verify.yml
